### ISSUE TITLE
How many environments and tasks do you have?

### ISSUE THREAD

**Issue by GoingMyWay** [columbia-robovision/decentralized-multiarm#1]
How many environments and tasks do you have? It is like Gym which provides many environments?

**Comment by huy-ha** [comment]
While there are a few different environment classes, they just abstract various features that the codebase uses. The only task this code base implements is multi-arm motion planning, and most of the functionality is in `environment/baseEnv.py`

**Comment by GoingMyWay** [comment]
> While there are a few different environment classes, they just abstract various features that the codebase uses. The only task this code base implements is multi-arm motion planning, and most of the functionality is in `environment/baseEnv.py`

Thank you. Should each arm work cooperatively to complete these tasks?

**Comment by huy-ha** [comment]
> Thank you. Should each arm work cooperatively to complete these tasks?
Yep! You can follow the instructions in the README.md to play around with them.

**Comment by GoingMyWay** [comment]
> > Thank you. Should each arm work cooperatively to complete these tasks?
> 
> Yep! You can follow the instructions in the README.md to play around with them.

Geat, cool, hope it can help my multi-agent RL research.
