### ISSUE TITLE
wget downloading problem

### ISSUE THREAD

**Issue by mamimaka** [columbia-robovision/decentralized-multiarm#11]
Hi @huy-ha, when I used wget to download raining tasks and expert demonstration dataset, it said, "Fail: reject the connection." Is there any other way to download raining tasks and expert demonstration dataset?

**Comment by mamimaka** [comment]
My download comends are 
wget https://multiarm.cs.columbia.edu/downloads/data/tasks.tar.xz
wget https://multiarm.cs.columbia.edu/downloads/data/expert.tar.xz

**Comment by huy-ha** [comment]
Thanks for your interest in our codebase. Unfortunately, Columbia CS's web servers are down at the moment. Sorry for the inconvenience. Could you try downloading using the same commands in a few hours?

**Comment by mamimaka** [comment]
> Thanks for your interest in our codebase. Unfortunately, Columbia CS's web servers are down at the moment. Sorry for the inconvenience. Could you try downloading using the same commands in a few hours?

Hi @huy-ha, I still can't download raining tasks and expert demonstration dataset, or enter the project web page(https://multiarm.cs.columbia.edu). Is there any other way to download these files？

Looking forward to your reply!

**Comment by huy-ha** [comment]
It should work now!
