### ISSUE TITLE
Gripper Open/Close

### ISSUE THREAD

**Issue by jiaqixuac** [columbia-robovision/decentralized-multiarm#2]
Hi,

It's a wonderful job!
I'm not very familiar with pybullet and not sure how to control the open and close of the gripper.
I read your https://github.com/columbia-robovision/decentralized-multiarm/tree/main/assets/gripper, but still not able to figure out.
Could you show how to open and close as in the animation of the last part of your paper?

**Comment by huy-ha** [comment]
Thanks! You can refer to my [Robotiq2F85](https://github.com/columbia-robovision/decentralized-multiarm/blob/b8f7c12df5b80fe7f9015f07ee46b9b5a508cb6e/environment/UR5.py#L55) class, in the functions `open()` and `close()`.
