### ISSUE TITLE
Command to run bin placing task?

### ISSUE THREAD

**Issue by ahundt** [columbia-robovision/decentralized-multiarm#4]
Hey, does this code currently include the bin placing task with the gripper?

I saw your comment here https://github.com/columbia-robovision/decentralized-multiarm/issues/1#issuecomment-728643176, but I wasn't sure.

If not, could that task and/or the command to run it be added?

**Comment by huy-ha** [comment]
We'll be looking into adding the code for that part soon! Thanks for your interest in the project!

**Comment by ahundt** [comment]
Thanks! I'm looking forward to it!

**Comment by huy-ha** [comment]
Hey there! My apologies for taking a while to get around to it. You'll find instructions for running the bin pick and place task as well as its visualization in Blender in `demo/`. I've updated the `environment.yml` file to include more dependencies which the demo needs, but they are just a few pip packages that you can install manually too.
