### ISSUE TITLE
Under what conditions will the program end training?

### ISSUE THREAD

**Issue by GuancongLuo** [columbia-robovision/decentralized-multiarm#7]
Hi @huy-ha ,

Decentralized-multiarm is interesting work. Thank you for your work.

I read the code carefully and didn't find any indicator to stop training.

Will the program automatically stop training? 

Or check whether the reward value reaches a certain value?

**Comment by huy-ha** [comment]
Thank you for your interest!

I did not implement any training stopper, you can kill it once you're happy with its performance.
